pipeline {
    agent none
    options {skipDefaultCheckout()}
    stages {
        stage('Run Tests'){
            parallel{
                stage('test on jdk-8') {
                    agent {docker {image 'maven:3.6.3-jdk-11'}}
                    steps {
                        sh 'mvn clean package'
                        sh 'mvn test'
                    }
                    post {
                        always {
                            junit 'target/surefire-reports/*.xml'
                        }
                    }
                }
                stage('test on jdk-11') {
                    agent {label 'slave_2'}
                    steps {
                        checkout scm
                        sh 'echo mvn -version'
                        sh 'mvn clean package'
                        sh 'mvn test'
                    }
                    post {
                        always {
                            junit 'target/surefire-reports/*.xml'
                        }
                    }
                }
            }
        }
        stage('Deliver') {
            parallel{
                stage('deliver on 8'){
                    agent {docker {image 'maven:3.6.3-jdk-8'}}
                    steps{ sh './jenkins/scripts/deliver.sh'}
                }
                stage('deliver on 11'){
                    agent {label 'slave_2'}
                    steps{ sh './jenkins/scripts/deliver.sh'}
                }
            }
        }
    }
}
