pipeline {
    agent none
    options {skipDefaultCheckout()}
    stages {
        stage('Build') {
            agent {docker {image 'maven:3.6.3-jdk-8'}}
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Test') {
            agent {docker {image 'maven:3.6.3-jdk-8'}}
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
             agent {docker {image 'maven:3.6.3-jdk-8'}}
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
